In [129]:
# Cairo University Faculty of Engineering
## Machine Learning
### Movies recommendation system
#### Name: Rahma Abdelkader mohmed

### Importing the needed libraries

In [130]:
import numpy as np
import pandas as pd

### Reading movies dataset

In [131]:
movies = pd.read_csv("C:/Users/DELL/Desktop/ContentBasedRecommenderSystem/movies.csv")
movies.head(5)

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

### Selecting the first 200 movies

In [132]:
movies_200 = movies.iloc[:200]
movies_200

movieId                                        title  \
0          1                             Toy Story (1995)   
1          2                               Jumanji (1995)   
2          3                      Grumpier Old Men (1995)   
3          4                     Waiting to Exhale (1995)   
4          5           Father of the Bride Part II (1995)   
..       ...                                          ...   
195      229                  Death and the Maiden (1994)   
196      230                     Dolores Claiborne (1995)   
197      231       Dumb & Dumber (Dumb and Dumber) (1994)   
198      232  Eat Drink Man Woman (Yin shi nan nu) (1994)   
199      233                               Exotica (1994)   

                                          genres  
0    Adventure|Animation|Children|Comedy|Fantasy  
1                     Adventure|Children|Fantasy  
2                                 Comedy|Romance  
3                           Comedy|Drama|Romance  
4                                         Comedy  
..                                           ...  
195                               Drama|Thriller  
196                               Drama|Thriller  
197                             Adventure|Comedy  
198                         Comedy|Drama|Romance  
199                                        Drama  

[200 rows x 3 columns]

### Reading ratings dataset associated with movieId

In [133]:
ratings=pd.read_csv("C:/Users/DELL/Desktop/ContentBasedRecommenderSystem/ratings.csv")
ratings.head(5)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

### Selecting the first 200 rating based on userId

In [134]:
Users_rating_200 = ratings[ratings['userId'] <= 200]
Users_rating_200

userId  movieId  rating   timestamp
0           1        1     4.0   964982703
1           1        3     4.0   964981247
2           1        6     4.0   964982224
3           1       47     5.0   964983815
4           1       50     5.0   964982931
...       ...      ...     ...         ...
29263     200    60074     3.5  1229887390
29264     200    61024     4.0  1229889835
29265     200    61323     4.0  1229887427
29266     200    62299     3.5  1229876803
29267     200    63433     4.0  1229887817

[29268 rows x 4 columns]

### Combine both datasets

In [135]:
combined_movies_data = pd.merge(Users_rating_200, movies_200, on='movieId')
combined_movies_data

userId  movieId  rating   timestamp                             title  \
0          1        1     4.0   964982703                  Toy Story (1995)   
1          5        1     4.0   847434962                  Toy Story (1995)   
2          7        1     4.5  1106635946                  Toy Story (1995)   
3         15        1     2.5  1510577970                  Toy Story (1995)   
4         17        1     4.5  1305696483                  Toy Story (1995)   
...      ...      ...     ...         ...                               ...   
2137     191      148     5.0   829760897  Awfully Big Adventure, An (1995)   
2138     191      155     4.0   829760897             Beyond Rangoon (1995)   
2139     191      178     1.0   829760898       Love & Human Remains (1993)   
2140     191      229     5.0   829760897       Death and the Maiden (1994)   
2141     199      229     3.0   940373078       Death and the Maiden (1994)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1     Adventure|Animation|Children|Comedy|Fantasy  
2     Adventure|Animation|Children|Comedy|Fantasy  
3     Adventure|Animation|Children|Comedy|Fantasy  
4     Adventure|Animation|Children|Comedy|Fantasy  
...                                           ...  
2137                                        Drama  
2138                          Adventure|Drama|War  
2139                                 Comedy|Drama  
2140                               Drama|Thriller  
2141                               Drama|Thriller  

[2142 rows x 6 columns]

### we won't need timestamp so we will drop it

In [136]:
combined_movies_data = combined_movies_data.drop(['timestamp'], axis=1)
combined_movies_data

userId  movieId  rating                             title  \
0          1        1     4.0                  Toy Story (1995)   
1          5        1     4.0                  Toy Story (1995)   
2          7        1     4.5                  Toy Story (1995)   
3         15        1     2.5                  Toy Story (1995)   
4         17        1     4.5                  Toy Story (1995)   
...      ...      ...     ...                               ...   
2137     191      148     5.0  Awfully Big Adventure, An (1995)   
2138     191      155     4.0             Beyond Rangoon (1995)   
2139     191      178     1.0       Love & Human Remains (1993)   
2140     191      229     5.0       Death and the Maiden (1994)   
2141     199      229     3.0       Death and the Maiden (1994)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1     Adventure|Animation|Children|Comedy|Fantasy  
2     Adventure|Animation|Children|Comedy|Fantasy  
3     Adventure|Animation|Children|Comedy|Fantasy  
4     Adventure|Animation|Children|Comedy|Fantasy  
...                                           ...  
2137                                        Drama  
2138                          Adventure|Drama|War  
2139                                 Comedy|Drama  
2140                               Drama|Thriller  
2141                               Drama|Thriller  

[2142 rows x 5 columns]

The function creates a pivot table from the combined_movies_data DataFrame, where the rows represent user IDs, the columns represent movie titles, and the values represent the corresponding ratings given by users to movies.
The function prints the size of the pivot table (number of rows and columns) and returns the pivot table.

In [137]:
def movies_rating_crosstable(combined_movies_data):
    movies_rating_crosstable_df = pd.pivot_table(
        data=combined_movies_data,
        values='rating',
        index='userId',
        columns='title',
        fill_value=0
    )
    print("The Pivot_table size = (userIDs, movie titles) = ", movies_rating_crosstable_df.shape)
    return movies_rating_crosstable_df

In [138]:
# creating the (Collaborative Filtering) CF tabel
movies_rating_transposed=movies_rating_crosstable(combined_movies_data)


The Pivot_table size = (userIDs, movie titles) =  (180, 176)


In [139]:
movies_rating_transposed.head(5)

title   Ace Ventura: When Nature Calls (1995)  \
userId                                          
1                                         0.0   
3                                         0.0   
4                                         0.0   
5                                         0.0   
6                                         2.0   

title   Amazing Panda Adventure, The (1995)  American President, The (1995)  \
userId                                                                        
1                                         0                             0.0   
3                                         0                             0.0   
4                                         0                             0.0   
5                                         0                             0.0   
6                                         4                             4.0   

title   Angels and Insects (1995)  Anne Frank Remembered (1995)  \
userId                                                            
1                               0                             0   
3                               0                             0   
4                               0                             0   
5                               0                             0   
6                               0                             0   

title   Antonia's Line (Antonia) (1995)  Apollo 13 (1995)  Assassins (1995)  \
userId                                                                        
1                                     0               0.0               0.0   
3                                     0               0.0               0.0   
4                                     0               0.0               0.0   
5                                     0               3.0               0.0   
6                                     0               4.0               0.0   

title   Awfully Big Adventure, An (1995)  Babe (1995)  ...  \
userId                                                 ...   
1                                      0          0.0  ...   
3                                      0          0.0  ...   
4                                      0          0.0  ...   
5                                      0          4.0  ...   
6                                      0          4.0  ...   

title   Unstrung Heroes (1995)  Up Close and Personal (1996)  \
userId                                                         
1                            0                           0.0   
3                            0                           0.0   
4                            0                           0.0   
5                            0                           0.0   
6                            3                           3.0   

title   Usual Suspects, The (1995)  Vampire in Brooklyn (1995)  \
userId                                                           
1                              5.0                           0   
3                              0.0                           0   
4                              0.0                           0   
5                              4.0                           0   
6                              1.0                           4   

title   Waiting to Exhale (1995)  Walk in the Clouds, A (1995)  \
userId                                                           
1                              0                           0.0   
3                              0                           0.0   
4                              0                           0.0   
5                              0                           0.0   
6                              3                           4.0   

title   Waterworld (1995)  White Man's Burden (1995)  White Squall (1996)  \
userId                                                                      
1                     0.0                          0                    0   
3                     0.0            

In [140]:
### checking the unique values for the first movie

In [141]:
movies_rating_transposed["Ace Ventura: When Nature Calls (1995)"].unique()

array([0. , 2. , 1. , 2.5, 4.5, 5. , 3.5, 3. , 1.5, 4. ])

### Transposing it to calculate the similarity matrix of item to item to be able to get the similarity scores

In [142]:
user_ratings_to_movies = movies_rating_transposed.transpose()
print("transpose Pivot tabel size = (movie titles , userIDs) = ",user_ratings_to_movies.shape)

transpose Pivot tabel size = (movie titles , userIDs) =  (176, 180)


In [143]:
user_ratings_to_movies.head(10)

userId                                 1    3    4    5    6    7    8    9    \
title                                                                           
Ace Ventura: When Nature Calls (1995)  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0   
Amazing Panda Adventure, The (1995)    0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0   
American President, The (1995)         0.0  0.0  0.0  0.0  4.0  0.0  4.0  0.0   
Angels and Insects (1995)              0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Anne Frank Remembered (1995)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Antonia's Line (Antonia) (1995)        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Apollo 13 (1995)                       0.0  0.0  0.0  3.0  4.0  4.5  4.0  0.0   
Assassins (1995)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Awfully Big Adventure, An (1995)       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Babe (1995)                            0.0  0.0  0.0  4.0  4.0  0.0  5.0  0.0   

userId                                 11   12   ...  191  192  193  194  195  \
title                                            ...                            
Ace Ventura: When Nature Calls (1995)  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Amazing Panda Adventure, The (1995)    0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
American President, The (1995)         0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Angels and Insects (1995)              0.0  0.0  ...  5.0  0.0  0.0  0.0  0.0   
Anne Frank Remembered (1995)           0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Antonia's Line (Antonia) (1995)        0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Apollo 13 (1995)                       5.0  0.0  ...  2.0  5.0  0.0  0.0  4.0   
Assassins (1995)                       0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Awfully Big Adventure, An (1995)       0.0  0.0  ...  5.0  0.0  0.0  0.0  0.0   
Babe (1995)                            0.0  0.0  ...  4.0  0.0  0.0  0.0  0.0   

userId                                 196  197  198  199  200  
title                                                           
Ace Ventura: When Nature Calls (1995)  0.0  0.0  0.0  0.0  3.5  
Amazing Panda Adventure, The (1995)    0.0  0.0  0.0  0.0  0.0  
American President, The (1995)         0.0  0.0  0.0  4.0  0.0  
Angels and Insects (1995)              0.0  0.0  0.0  1.0  0.0  
Anne Frank Remembered (1995)           0.0  0.0  0.0  0.0  0.0  
Antonia's Line (Antonia) (1995)        0.0  0.0  0.0  0.0  0.0  
Apollo 13 (1995)                       5.0  0.0  0.0  4.0  4.0  
Assassins (1995)                       0.0  0.0  0.0  0.0  0.0  
Awfully Big Adventure, An (1995)       0.0  0.0  0.0  0.0  0.0  
Babe (1995)                            0.0  0.0  4.0  0.0  2.5  

[10 rows x 180 columns]

### Calculate the cosine similarity between items (movies)

In [144]:
from sklearn.metrics.pairwise import cosine_similarity

def calculate_item_similarity(user_ratings_to_movies):
    
    similarity_scores_movies = cosine_similarity(user_ratings_to_movies)
    print("Shape of the similarity matrix: ", similarity_scores_movies.shape)
    print(similarity_scores_movies)
    return similarity_scores_movies


In [145]:
similarity_scores_movies=calculate_item_similarity(user_ratings_to_movies)

Shape of the similarity matrix:  (176, 176)
[[1.         0.16657816 0.33700144 ... 0.13875846 0.11696329 0.11100677]
 [0.16657816 1.         0.23501216 ... 0.68599434 0.51399405 0.85749293]
 [0.33700144 0.23501216 1.         ... 0.19576351 0.34836373 0.27406892]
 ...
 [0.13875846 0.68599434 0.19576351 ... 1.         0.46829291 0.8       ]
 [0.11696329 0.51399405 0.34836373 ... 0.46829291 1.         0.59941492]
 [0.11100677 0.85749293 0.27406892 ... 0.8        0.59941492 1.        ]]


### Creating dataframe with the movies titles and similarity

In [146]:
data_matrix_item = pd.DataFrame(data=similarity_scores_movies, index=user_ratings_to_movies.transpose().columns, columns=user_ratings_to_movies.transpose().columns)

In [147]:
data_matrix_item.head(10)

title                                  Ace Ventura: When Nature Calls (1995)  \
title                                                                          
Ace Ventura: When Nature Calls (1995)                               1.000000   
Amazing Panda Adventure, The (1995)                                 0.166578   
American President, The (1995)                                      0.337001   
Angels and Insects (1995)                                           0.000000   
Anne Frank Remembered (1995)                                        0.000000   
Antonia's Line (Antonia) (1995)                                     0.080112   
Apollo 13 (1995)                                                    0.388591   
Assassins (1995)                                                    0.104858   
Awfully Big Adventure, An (1995)                                    0.000000   
Babe (1995)                                                         0.342358   

title                                  Amazing Panda Adventure, The (1995)  \
title                                                                        
Ace Ventura: When Nature Calls (1995)                             0.166578   
Amazing Panda Adventure, The (1995)                               1.000000   
American President, The (1995)                                    0.235012   
Angels and Insects (1995)                                         0.000000   
Anne Frank Remembered (1995)                                      0.000000   
Antonia's Line (Antonia) (1995)                                   0.297044   
Apollo 13 (1995)                                                  0.232556   
Assassins (1995)                                                  0.155520   
Awfully Big Adventure, An (1995)                                  0.000000   
Babe (1995)                                                       0.298277   

title                                  American President, The (1995)  \
title                                                                   
Ace Ventura: When Nature Calls (1995)                        0.337001   
Amazing Panda Adventure, The (1995)                          0.235012   
American President, The (1995)                               1.000000   
Angels and Insects (1995)                                    0.022456   
Anne Frank Remembered (1995)                                 0.000000   
Antonia's Line (Antonia) (1995)                              0.000000   
Apollo 13 (1995)                                             0.520100   
Assassins (1995)                                             0.157799   
Awfully Big Adventure, An (1995)                             0.000000   
Babe (1995)                                                  0.410753   

title                                  Angels and Insects (1995)  \
title                                                              
Ace Ventura: When Nature Calls (1995)                   0.000000   
Amazing Panda Adventure, The (1995)                     0.000000   
American President, The (1995)                          0.022456   
Angels and Insects (1995)                               1.000000   
Anne Frank Remembered (1995)                            0.573539   
Antonia's Line (Antonia) (1995)                         0.331133   
Apollo 13 (1995)                                        0.131876   
Assassins (1995)                                        0.000000   
Awfully Big Adventure, An (1995)                        0.573539   
Babe (1995)                                             0.208784   

title                                  Anne Frank Remembered (1995)  \
title                                                                 
Ace Ventura: When Nature Calls (1995)                      0.000000   
Amazing Panda Adventure, The (1995)                        0.000000   
American President, The (1995)                             0.000000   
Angels and Insects (1995)                            

### function that takes the name of the movie and the number of recommendations

In [148]:
def recommend_movies_similar_to_movie(movie, recomemnds=10):
    movie = movie
    number_of_recommendation = recomemnds

    # in data_matrix movie titles were set to be the indices ad then saving the indices means savng the mavie titles
    indices = data_matrix_item.loc[movie].nlargest(
        number_of_recommendation+1).index

    print("The recommended movies if u like '{}' are \n".format(movie))
    for idx, num in enumerate(indices):
        if idx > 0:
            print(num)

### Top 10 movies similar to 'Toy Story (1995)'

In [149]:
recommend_movies_similar_to_movie('Toy Story (1995)')


The recommended movies if u like 'Toy Story (1995)' are 

Braveheart (1995)
Apollo 13 (1995)
Usual Suspects, The (1995)
Happy Gilmore (1996)
Die Hard: With a Vengeance (1995)
Seven (a.k.a. Se7en) (1995)
Babe (1995)
Waterworld (1995)
Batman Forever (1995)
Taxi Driver (1976)


### Top 10 movies similar to 'Waiting to Exhale (1995)'

In [150]:
recommend_movies_similar_to_movie('Waiting to Exhale (1995)')

The recommended movies if u like 'Waiting to Exhale (1995)' are 

Before and After (1996)
Mighty Morphin Power Rangers: The Movie (1995)
Before the Rain (Pred dozhdot) (1994)
Bushwhacked (1995)
Cure, The (1995)
Georgia (1995)
Mad Love (1995)
Now and Then (1995)
Reckless (1995)
Three Wishes (1995)


### Calculate the similarity matrix for the users

In [151]:
similarity_scores_user = cosine_similarity(user_ratings_to_movies.transpose())
similarity_scores_user.shape

(180, 180)

### Saving the unique userIDS

In [152]:
user_ids = np.unique(combined_movies_data["userId"])

### Creating a dataframe where similarity matrix for useres is the data , columns and indices are the user IDS

In [153]:
data_matrix_user = pd.DataFrame(data=similarity_scores_user, index=user_ids, columns=user_ids)

### Recommend movies for a certain user based on similar users

In [154]:
def recommend_movies_for_user(userID, recommends, similar_users=5):
    #catching function args
    userID = userID
    number_of_similar_users = similar_users
    number_of_recommendation = recommends

    counter = 0
    # save the ids of similar users
    indices = data_matrix_user.loc[userID].nlargest(number_of_similar_users+1).index

    print("the recommended movies for user {}".format(userID))

    # loop on similar users and print indices
    
    for idx, num in enumerate(indices):
        # save all the movies that this user watched with high ratings
        movie_rec_user = movies_rating_transposed.loc[indices[idx]].nlargest(
            number_of_recommendation+1).index

        # lopp over those movies with high ratings
        for idx, num in enumerate(movie_rec_user):

            # check if the user have watched it or not (if user rated that movie or not)
            if (movies_rating_transposed[movie_rec_user[idx]].loc[userID] == 0) & (counter < number_of_recommendation):

                # if he haven't watched it recommend the movie
                print(movie_rec_user[idx])
                counter += 1

### Printing three recommendations for userId 200

In [155]:
recommend_movies_for_user(userID=200,recommends=3)

the recommended movies for user 200
First Knight (1995)
Usual Suspects, The (1995)
Pocahontas (1995)
